version: '3'

services:
  app:
    container_name: openvagas-portal
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '80:80'
    networks: 
      - ngps

networks:
  ngps:
    external:
      name: ngps